[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'
solc-version = "0.8.23"
no-match-path = 'test/kontrol/*'
extra_output = ['storageLayout', 'abi']

[profile.kprove]
src = 'test/kontrol'
out = 'kout'
test = 'test/kontrol'

[fmt]
multiline_func_header = 'params_first'
